name: Build
on: [push]
jobs:
  linux-builds:
    name: "linux build"
    runs-on: ubuntu-latest
    steps:
      - name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
        id: go

      - name: "Check out code"
        uses: actions/checkout@v1

      - name: "build"
        run: |
          go build ./...

      - name: "test"
        run: |
          go test ./...
